sudo: required
services:
    - docker

before_install:
    - docker build -t devopsothman/multiple-docker -f ./client/Dockerfile.dev ./client 
script:
    - docker run -e CI=true devopsothman/multiple-docker npm run test -- --coverage
after_success:
    - docker build -t devopsothman/multiple-client ./client
    - docker build -t devopsothman/multiple-nginx ./nginx
    - docker build -t devopsothman/multiple-server ./server
    - docker build -t devopsothman/multiple-worker ./worker
# login to docker cli
echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin 
# push built images into docker hup
docker push devopsothman/multiple-client
docker push devopsothman/multiple-nginx
docker push devopsothman/multiple-server
docker push devopsothman/multiple-worker